### ISSUE TITLE
the web server dose not run after installation.

### ISSUE THREAD

**Issue by MRSheikh** [Nirob3x/OpenVPN-As-Unlimited#2]
hi.
i installed it on my centos 7 vps . the web server dose not run after installation  and so i cannot access admin panel.

**Comment by Nirob3x** [comment]
is your VPS  from DigitalOcean? I have created this script for DigitalOcean server only .  please double check your server first.

**Comment by MRSheikh** [comment]
thanks

**Comment by facade1337** [comment]
Hi there -- I have a mirror of this repository designed to work on any VPS.
Please LMK if this solved your issue. 
[Repo](https://github.com/facade1337/ovpnas)
