### ISSUE TITLE
Update to Newest OPENVPNAS

### ISSUE THREAD

**Issue by pebu1337** [Nirob3x/OpenVPN-As-Unlimited#3]
Hi there,
Do you have any idea how we would update to the latest version of openvpn AS?
Thanks.

**Comment by gjf** [comment]
No way :)
The author copied the solution from one of Russian forums. Now as OpenVPN AS moves to Python 3 - the original author did not update files to latest version. 
So we are stuck )

**Comment by Nirob3x** [comment]
@gjf 
You can search over the internet before posting comments. 
also, I have more updated files that I don't wanna public for free.
Thank You.

**Comment by gjf** [comment]
> @gjf 
> You can search over the internet before posting comments. 
> also, I have more updated files that I don't wanna public for free.
> Thank You.
> 

Again copied my posts?
Beware - they are watermarked. )))

**Comment by Nirob3x** [comment]
Check Out Here,  https://imgur.com/a/vowHKpi
If you have proven that it's your project then mail me the proof, I will delete everything.  if you don't then stop it go to sleep. people from the world don't gonna read your local language blog. 
I don't care, you are not the first people, there are 15+ people who mailed me that they are the author, haha ;)
