### ISSUE TITLE
nirob.info is unavailable

### ISSUE THREAD

**Issue by mshadow73** [Nirob3x/OpenVPN-As-Unlimited#4]
Hi 
I keep getting this error could you please help me with this?
I used to install this server and in the end it asked for a password but recently it gives me this error

Nothing to do
--2021-04-08 09:28:16--  http://nirob.info/OpenVPN/openvpn-as-2.5-CentOS7.x86_64.rpm
Resolving nirob.info (nirob.info)... failed: Name or service not known.
wget: unable to resolve host address ‘nirob.info’
error: open of openvpn-as-2.5-CentOS7.x86_64.rpm failed: No such file or directory
./centos7.sh: line 15: cd: /usr/local/openvpn_as/lib/python2.7/site-packages/: No such file or directory
rm: cannot remove ‘pyovpn-2.0-py2.7.egg’: No such file or directory
--2021-04-08 09:28:18--  http://nirob.info/OpenVPN/pyovpn-2.0-py2.7.egg
Resolving nirob.info (nirob.info)... failed: Name or service not known.
wget: unable to resolve host address ‘nirob.info’
./centos7.sh: line 18: cd: /usr/local/openvpn_as/bin: No such file or directory
./centos7.sh: line 19: ./ovpn-init: No such file or directory

**Comment by facade1337** [comment]
Hey there -- no clue if you still need this but I have a mirror of this repository with the rpm and the egg. 
[Repo](https://github.com/facade1337/ovpnas)

**Comment by Nirob3x** [comment]
Hey , This error fixed
