### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by dotercan** [Nirob3x/OpenVPN-As-Unlimited#8]
Hi, 

When trying to install on CentOS 7 it seems to be not working. Can you assist? Bellow you can see the install output/log

`  / __|___ _ _| |_ / _ \/ __|__  |
 | (__/ -_) ' \  _| (_) \__ \ / /
  \___\___|_||_\__|\___/|___//_/
 OpenVPN Access Server With Unlimited License BY Nirob3x
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.neostrada.nl
 * extras: mirror.neostrada.nl
 * updates: mirror.sitbv.nl
No packages marked for update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.neostrada.nl
 * extras: mirror.neostrada.nl
 * updates: mirror.sitbv.nl
Package wget-1.14-18.el7_6.1.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.neostrada.nl
 * extras: mirror.neostrada.nl
 * updates: mirror.sitbv.nl
Package net-tools-2.0-0.25.20131004git.el7.x86_64 already installed and latest version
Nothing to do
--2021-11-12 16:24:21--  https://nirob.info/OpenVPN/openvpn-as-2.5-CentOS7.x86_64.rpm
Resolving nirob.info (nirob.info)... 104.21.46.245, 172.67.169.135, 2606:4700:3034::6815:2ef5, ...
Connecting to nirob.info (nirob.info)|104.21.46.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35039736 (33M)
Saving to: ‘openvpn-as-2.5-CentOS7.x86_64.rpm.2’

100%[===================================================================================================================================================================================================>] 35,039,736  14.0MB/s   in 2.4s

2021-11-12 16:24:23 (14.0 MB/s) - ‘openvpn-as-2.5-CentOS7.x86_64.rpm.2’ saved [35039736/35039736]

        package openvpn-as-0:2.5-CentOSrelease.x86_64 is already installed
--2021-11-12 16:24:24--  https://nirob.info/OpenVPN/pyovpn-2.0-py2.7.egg
Resolving nirob.info (nirob.info)... 104.21.46.245, 172.67.169.135, 2606:4700:3034::6815:2ef5, ...
Connecting to nirob.info (nirob.info)|104.21.46.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1867061 (1.8M)
Saving to: ‘pyovpn-2.0-py2.7.egg’

100%[===================================================================================================================================================================================================>] 1,867,061   9.90MB/s   in 0.2s

2021-11-12 16:24:24 (9.90 MB/s) - ‘pyovpn-2.0-py2.7.egg’ saved [1867061/1867061]

Detected an existing OpenVPN-AS configuration.
Continuing will delete this configuration and restart from scratch.
Please enter 'DELETE' to delete existing configuration: delete
OpenVPN-AS configuration has not been modified.
=========================DONE==============================
SETUP ADMIN PASSWORD
Changing password for user openvpn.
New password:
Retype new password:
passwd: all authentication tokens updated successfully.
=========================DONE==============================
===================Telegram Help +1 731 203 2777 =============
[root@vps ~]#
`

**Comment by Nirob3x** [comment]
Please Try with Digitalocan.
